<?php     

return [
    'medical_annual_limit'=>100000,
    'thanksgiving_percent'=>1000,
//    'transaction_fee'=>0.0150,
    'transaction_fee'=>0,
    'transaction_fee_min' => 0.50, // not applicable for kiple
    'corporate_tax'=>0.06,
    'datetime_format'=>'d/m/Y H:i',
    'datetime_second_format'=>'d/m/Y H:i:s',
    'date_format'=>'d/m/Y',
    'time_format'=>'H:i',
    'assignment_form'=>'documents/assignment/ABSOLUTE_ASSIGNMENT_FORM_Charity_20210603.docx',
	'freelook_days' => 14,

    'area'=>'User',
    'zenDeskSecret'=>'0DF03DBCB4EFCFF0CD55491747E3C29B960BA29917D6C0802E1B3067EEDEFD97',
    'allowed_routes'=>[
        'admin.auth.login',
        'admin.auth.logout',
        'admin.dashboard.main',
        'admin.password.request',
        'admin.password.email',
        'admin.password.reset',
        'admin.password.update',
    ],
    'claim_documents'=>[
        'doc1',
        'doc2',
        'doc3',
        'doc4',
        'doc5',
    ],
    'relation_ships'=>[
      'spouse',
      'child',
      'parent',
      'parent_in_law',
      'sibling',
      'sibling_in_law',
      'grandparent',
      'other',
    ],
    'relation_ships_buy_for_other'=>[
        'spouse',
        'child',
        'parent',
        'sibling',
        'grandchildren',
        'other',
    ],
    'banks'=>[
        "MALAYAN BANKING BERHAD",
        "AFFIN BANK BERHAD / AFFIN ISLAMIC BANK",
        "AL-RAJHI BANKING & INVESTMENT CORP (M) BERHAD",
        "ALLIANCE BANK MALAYSIA BERHAD",
        "AmBANK BERHAD",
        "BANK ISLAM MALAYSIA",
        "BANK KERJASAMA RAKYAT MALAYSIA BERHAD",
        "BANK MUAMALAT",
        "BANK OF AMERICA",
        "BANK OF CHINA (MALAYSIA) BERHAD",
        "BANK PERTANIAN MALAYSIA BERHAD (AGROBANK)",
        "BANK SIMPANAN NASIONAL BERHAD",
        "BNP PARIBAS MALAYSIA",
        "Bangkok Bank Berhad",
        "CHINA CONST BK (M) BHD",
        "CIMB BANK BERHAD",
        "CITIBANK BERHAD",
        "DEUTSCHE BANK (MSIA) BERHAD",
        "HONG LEONG BANK",
        "HSBC BANK MALAYSIA BERHAD",
        "INDUSTRIAL &amp; COMMERCIAL BANK OF CHINA",
        "J.P. MORGAN CHASE BANK BERHAD",
        "KUWAIT FINANCE HOUSE (MALAYSIA) BHD",
        "MBSB BANK BERHAD",
        "MIZUHO CORPORATE BANK MALAYSIA",
        "MUFG BANK (MALAYSIA) BHD",
        "OCBC BANK(MALAYSIA) BHD",
        "PUBLIC BANK",
        "RHB BANK",
        "STANDARD CHARTERED BANK",
        "SUMITOMO MITSUI BANKING CORPORATION MALAYSIA BHD",
        "UNITED OVERSEAS BANK BERHAD",
    ],
    'relationships'=>[
        //'Customer'=>'Customer',
        'Medical Panel'=>'Panel Clinic',
        //'Charity Foundation'=>'Charity Foundation',
       // 'Business Partner'=>'Business Partner',
        'Panel Hospital'=>'Panel Hospital',
    ],
    'status_list'=>[
        'Draft',
        'Pending',
        'Processing',
        'Rejected',
        'Cancelled',
        'Processed',
    ],
    'nationalities'=>
        [
            "Afghan",
            "Albanian",
            "Algerian",
            "American",
            "Andorran",
            "Angolan",
            "Antiguans",
            "Argentinean",
            "Armenian",
            "Australian",
            "Austrian",
            "Azerbaijani",
            "Bahamian",
            "Bahraini",
            "Bangladeshi",
            "Barbadian",
            "Barbudans",
            "Batswana",
            "Belarusian",
            "Belgian",
            "Belizean",
            "Beninese",
            "Bhutanese",
            "Bolivian",
            "Bosnian",
            "Brazilian",
            "British",
            "Bruneian",
            "Bulgarian",
            "Burkinabe",
            "Burmese",
            "Burundian",
            "Cambodian",
            "Cameroonian",
            "Canadian",
            "Cape Verdean",
            "Central African",
            "Chadian",
            "Chilean",
            "Chinese",
            "Colombian",
            "Comoran",
            "Congolese",
            "Costa Rican",
            "Croatian",
            "Cuban",
            "Cypriot",
            "Czech",
            "Danish",
            "Djibouti",
            "Dominican",
            "Dutch",
            "East Timorese",
            "Ecuadorean",
            "Egyptian",
            "Emirian",
            "Equatorial Guinean",
            "Eritrean",
            "Estonian",
            "Ethiopian",
            "Fijian",
            "Filipino",
            "Finnish",
            "French",
            "Gabonese",
            "Gambian",
            "Georgian",
            "German",
            "Ghanaian",
            "Greek",
            "Grenadian",
            "Guatemalan",
            "Guinea-Bissauan",
            "Guinean",
            "Guyanese",
            "Haitian",
            "Herzegovinian",
            "Honduran",
            "Hungarian",
            "I-Kiribati",
            "Icelander",
            "Indian",
            "Indonesian",
            "Iranian",
            "Iraqi",
            "Irish",
            "Israeli",
            "Italian",
            "Ivorian",
            "Jamaican",
            "Japanese",
            "Jordanian",
            "Kazakhstani",
            "Kenyan",
            "Kittian and Nevisian",
            "Kuwaiti",
            "Kyrgyz",
            "Laotian",
            "Latvian",
            "Lebanese",
            "Liberian",
            "Libyan",
            "Liechtensteiner",
            "Lithuanian",
            "Luxembourger",
            "Macedonian",
            "Malagasy",
            "Malawian",
            "Malaysian",
            "Maldivan",
            "Malian",
            "Maltese",
            "Marshallese",
            "Mauritanian",
            "Mauritian",
            "Mexican",
            "Micronesian",
            "Moldovan",
            "Monacan",
            "Mongolian",
            "Moroccan",
            "Mosotho",
            "Motswana",
            "Mozambican",
            "Namibian",
            "Nauruan",
            "Nepalese",
            "New Zealander",
            "Nicaraguan",
            "Nigerian",
            "Nigerien",
            "North Korean",
            "Northern Irish",
            "Norwegian",
            "Omani",
            "Pakistani",
            "Palauan",
            "Panamanian",
            "Papua New Guinean",
            "Paraguayan",
            "Peruvian",
            "Polish",
            "Portuguese",
            "Qatari",
            "Romanian",
            "Russian",
            "Rwandan",
            "Saint Lucian",
            "Salvadoran",
            "Samoan",
            "San Marinese",
            "Sao Tomean",
            "Saudi",
            "Scottish",
            "Senegalese",
            "Serbian",
            "Seychellois",
            "Sierra Leonean",
            "Singaporean",
            "Slovakian",
            "Slovenian",
            "Solomon Islander",
            "Somali",
            "South African",
            "South Korean",
            "Spanish",
            "Sri Lankan",
            "Sudanese",
            "Surinamer",
            "Swazi",
            "Swedish",
            "Swiss",
            "Syrian",
            "Taiwanese",
            "Tajik",
            "Tanzanian",
            "Thai",
            "Togolese",
            "Tongan",
            "Trinidadian or Tobagonian",
            "Tunisian",
            "Turkish",
            "Tuvaluan",
            "Ugandan",
            "Ukrainian",
            "Uruguayan",
            "Uzbekistani",
            "Venezuelan",
            "Vietnamese",
            "Welsh",
            "Yemenite",
            "Zambian",
            "Zimbabwean"
        ],
    'product_documents'=>[
        [
            "title" => ('mobile.product_disclosure_sheet'),
            "link"  => 'https://docs.google.com/viewer?url=http://dev.deartime.com/documents/PDS-Death.pdf',
            "type"  => "pdf"
        ],
        [
            "title" => ('mobile.contract'),
            "link"  => 'https://docs.google.com/viewer?url=http://dev.deartime.com/documents/Contract-Death.pdf',
        ],
        [
            "title" => ('mobile.financial_calculator'),
            "link"  => 'https://www.deartime.com/calculator/',
        ],
        [
            "title" => ('mobile.faq'),
            "link"  => '',
        ],
    ],

	'underwriting' => [
		'allow_daily_smoke' => 30
	],

	'death_docs' => [
		//['name' => 'APS- Death','link' => resource_path('documents/claims/death/1._DS_-_Death_for_PH_20201017.xlsm')],
		['name' => 'APS- Death','link' => base64_encode('documents/claims/death/1._DS_-_Death_for_PH_20201017.xlsm')],
		['name' => 'Post Mortem','link' => NULL],
		['name' => 'Toxicology Report','link' => NULL],
		//['name' => 'Consent','link' => resource_path('documents/claims/common/Consent_For_The_Release_of_Information_form.docx')],
		['name' => 'Consent','link' => null],
	],

	'disability_docs' => [
		//['name' => 'APS- Disability','link' => resource_path('documents/claims/disability/1._DS_-_Disability_for_PH_20201017.xlsm')],
		['name' => 'APS- Disability','link' => base64_encode('documents/claims/disability/1._DS_-_Disability_for_PH_20201017.xlsm')],
		['name' => 'Other','link' => NULL],
		//['name' => 'Consent','link' => resource_path('documents/claims/common/Consent_For_The_Release_of_Information_form.docx')],
		['name' => 'Consent','link' => null],
	],



];
